version: "3.9"
services: 
  app:
    container_name: node
    build: 
      context: ./docker/app
      dockerfile: ./Dockerfile
    volumes: 
      - .:/var/www/nestjs/mobssosa
    ports: 
      - 3000:3000
      - 9229:9229
    tty: true
    networks: 
      - mobssosa-networks

  es01:
    container_name: es01
    build:
      context: ./docker/search
      dockerfile: ./Dockerfile
    environment: 
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./docker/search/data01:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
    networks: 
      - mobssosa-networks

  es02:
    container_name: es02
    build:
      context: ./docker/search
      dockerfile: ./Dockerfile
    environment: 
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./docker/search/data02:/usr/share/elasticsearch/data
    ports: 
      - 9201:9201
    networks: 
      - mobssosa-networks
      
  es03:
    container_name: es03
    build:
      context: ./docker/search
      dockerfile: ./Dockerfile
    environment: 
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./docker/search/data03:/usr/share/elasticsearch/data
    ports: 
      - 9202:9202
    networks: 
      - mobssosa-networks

  kibana:
    container_name: kibana
    image: kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - mobssosa-networks
    ports:
      - 5601:5601
    
  db:
    build:
      context: .
      dockerfile: ./docker/data/Dockerfile
    container_name: db
    secrets:
        - mysql-root
        - mysql-user
    environment:
        MYSQL_DATABASE: node
        MYSQL_USER: root
        MYSQL_PASSWORD: /run/secrets/mysql-user
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
    ports:
        - "3306:3306"
    expose:
        - "3306"
    volumes:
        - "./docker/data/mysql:/var/lib/mysql"
        - "./docker/data/pw:/run/secrets"
        - "./docker/mysql/logs:/var/log/mysql"
    command: --sql_mode=""
    restart: always
    networks:
        - mobssosa-networks

volumes: 
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks: 
  mobssosa-networks:
    driver: bridge

secrets:
  mysql-root:
    file: ./docker/data/secrets/mysql-root
  mysql-user:
    file: ./docker/data/secrets/mysql-user